In [1]:
import os

from keras.preprocessing.image import ImageDataGenerator

import PIL
from PIL import Image

import numpy as np
import cv2

C:\Users\COEGIN\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
alphabet = {"0": 0, "1": 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, 'a': 10, 'b': 11,
            'c': 12, 'd': 13, 'e': 14, 'f': 15, 'g': 16, 'h': 17, 'i': 18, 'j': 19, 'k': 20, 'l': 21, 'm': 22,
            'n': 23, 'o': 24, 'p': 25, 'q': 26, 'r': 27, 's': 28, 't': 29, 'u': 30, 'v': 31, 'w': 32,
            'x': 33, 'y': 34, 'z': 35 } 

In [ ]:
print(alphabet)

In [ ]:
# Needed for transformation of character to number.
def char_to_num(char):
    num = alphabet[char]
    return num


# Needed for transformation of number to character.
def num_to_char(num):
    for key in alphabet:
        if alphabet[key] == num:
            return key


# Load file paths and labels them.
def load_chars74k_data(dir="chars74k-lite"):
    filenames = []
    label_list = []
    
    for path, dirs, files in os.walk(dir):
        for file in files:
            if file.endswith('.jpg'):
                file = path + '/' + file
                filenames.append(file)

                label = path[-1:]
                label_list.append(label)

    return filenames, label_list


# Creates the dataset.
def create_dataset(file_paths, label_set, with_denoising=False):
    data_x = []
    data_y = []

    for path in file_paths:
        single_x = np.asarray(PIL.Image.open(path)).flatten()

        # Denoise image with help of OpenCV (increase time of computing).
        if with_denoising:
            single_x = cv2.fastNlMeansDenoising(single_x).flatten()
        data_x.append(single_x)

    for l in label_set:
        l_to_num = char_to_num(l)
        data_y.append(l_to_num)

    np_data_x = np.array(data_x)
    np_data_y = np.array(data_y)
    return np_data_x, np_data_y


# Use the Keras data generator to augment data.
def create_datagenerator(x_train, x_test, y_train, y_test):
    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        rotation_range=0. / 180,
        vertical_flip=True)

    test_datagen = ImageDataGenerator(rescale=1. / 255)

    train_generator = train_datagen.flow(x=x_train, y=y_train)
    validation_generator = test_datagen.flow(x=x_test, y=y_test)

    return train_generator, validation_generator


In [3]:
# Load file paths and labels them.
dir="chars74k-lite"
filenames = []
label_list = []
    
for path, dirs, files in os.walk(dir):
    for file in files:
        if file.endswith('.jpg'):
            file = path + '/' + file
            filenames.append(file)

            label = path[-1:]
            label_list.append(label)

#print(filenames)
print(label_list)

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',

In [11]:
with_denoising=False
data_x = []
data_y = []

for path in filenames:
    single_x = np.asarray(PIL.Image.open(path)).flatten()
    data_x.append(single_x)
#      # Denoise image with help of OpenCV (increase time of computing).
#      if with_denoising:
#         single_x = cv2.fastNlMeansDenoising(single_x).flatten()
     

for l in label_list:
    l_to_num = alphabet[l]
    data_y.append(l_to_num)

np_data_x = np.array(data_x)
np_data_y = np.array(data_y)
print(np_data_x)
print(np_data_y)

[[249 255 243 ... 255 255 255]
 [254 255 252 ... 255 255 255]
 [255 255 250 ... 255 255 255]
 ...
 [252 249 247 ... 227 225 224]
 [178 202 110 ... 195  27  26]
 [174 163 182 ... 178 167 156]]
[ 0  0  0 ... 35 35 35]
